export interface FitSportMapping {
  sport: string;
  subSport: string;
  warning?: string;
}

const POLAR_FLOW_SPORT_ID_TO_KIND: Record<string, string> = {
  '1': 'RUNNING',
  '2': 'CYCLING',
  '3': 'WALKING',
  '4': 'JOGGING',
  '5': 'MOUNTAIN_BIKING',
  '6': 'CROSS_COUNTRY_SKIING',
  '7': 'DOWNHILL_SKIING',
  '8': 'ROWING',
  '9': 'NORDIC_WALKING',
  '10': 'SKATING',
  '11': 'HIKING',
  '12': 'TENNIS',
  '13': 'SQUASH',
  '14': 'BADMINTON',
  '15': 'STRENGTH_TRAINING',
  '16': 'OTHER_OUTDOOR',
  '17': 'TREADMILL_RUNNING',
  '18': 'INDOOR_CYCLING',
  '19': 'ROAD_RUNNING',
  '20': 'CIRCUIT_TRAINING',
  '22': 'SNOWBOARDING',
  '23': 'SWIMMING',
  '24': 'XC_SKIING_FREESTYLE',
  '25': 'XC_SKIING_CLASSIC',
  '27': 'TRAIL_RUNNING',
  '28': 'ICE_SKATING',
  '29': 'INLINE_SKATING',
  '30': 'ROLLER_BLADING',
  '32': 'GROUP_EXERCISE',
  '33': 'YOGA',
  '34': 'HIIT',
  '35': 'GOLF',
  '36': 'TRACK_AND_FIELD_RUNNING',
  '38': 'ROAD_BIKING',
  '39': 'SOCCER',
  '40': 'CRICKET',
  '41': 'BASKETBALL',
  '42': 'BASEBALL',
  '43': 'RUGBY',
  '44': 'FIELD_HOCKEY',
  '45': 'VOLLEYBALL',
  '46': 'ICE_HOCKEY',
  '47': 'AMERICAN_FOOTBALL',
  '48': 'HANDBALL',
  '49': 'BEACH_VOLLEYBALL',
  '50': 'FUTSAL',
  '51': 'FLOORBALL',
  '52': 'DANCING',
  '53': 'TROTTING',
  '54': 'RIDING',
  '55': 'CROSS_TRAINER',
  '56': 'FITNESS_MARTIAL_ARTS',
  '57': 'FUNCTIONAL_TRAINING',
  '58': 'BOOTCAMP',
  '59': 'ROLLER_SKIING_FREESTYLE',
  '60': 'ROLLER_SKIING_CLASSIC',
  '61': 'AEROBICS',
  '62': 'AQUATICS',
  '63': 'FITNESS_STEP',
  '64': 'BODY_AND_MIND',
  '65': 'PILATES',
  '66': 'STRETCHING',
  '67': 'FITNESS_DANCING',
  '68': 'TRIATHLON',
  '69': 'DUATHLON',
  '70': 'OFFROADTRIATHLON',
  '71': 'OFFROADDUATHLON',
  '72': 'TRIATHLON_RUNNING',
  '73': 'TRIATHLON_SWIMMING',
  '74': 'TRIATHLON_CYCLING',
  '75': 'DUATHLON_RUNNING',
  '76': 'DUATHLON_CYCLING',
  '77': 'OFFROADTRIATHLON_RUNNING',
  '78': 'OFFROADTRIATHLON_SWIMMING',
  '79': 'OFFROADTRIATHLON_CYCLING',
  '80': 'OFFROADDUATHLON_RUNNING',
  '81': 'OFFROADDUATHLON_CYCLING',
  '82': 'FREE_MULTISPORT',
  '83': 'OTHER_INDOOR',
  '84': 'ORIENTEERING',
  '85': 'ORIENTEERING_SKI',
  '86': 'ORIENTEERING_MTB',
  '87': 'BIATHLON',
  '88': 'WATERSPORTS_SAILING',
  '89': 'PARASPORTS_WHEELCHAIR',
  '90': 'FRISBEEGOLF',
  '91': 'TABLE_TENNIS',
  '92': 'ULTRARUNNING_RUNNING',
  '94': 'VERTICALSPORTS_WALLCLIMBING',
  '95': 'WATERSPORTS_KAYAKING',
  '96': 'WATERSPORTS_CANOEING',
  '100': 'WATERSPORTS_KITESURFING',
  '101': 'WATERSPORTS_WINDSURFING',
  '102': 'WATERSPORTS_SURFING',
  '103': 'POOL_SWIMMING',
  '104': 'FINNISH_BASEBALL',
  '105': 'OPEN_WATER_SWIMMING',
  '107': 'WATERSPORTS_WAKEBOARDING',
  '108': 'WATERSPORTS_WATERSKI',
  '109': 'BOXING',
  '110': 'KICKBOXING_MARTIAL_ARTS',
  '111': 'MOBILITY_DYNAMIC',
  '112': 'TELEMARK_SKIING',
  '113': 'BACKCOUNTRY_SKIING',
  '114': 'GYMNASTICK',
  '115': 'JUDO_MARTIAL_ARTS',
  '116': 'SNOWSHOE_TREKKING',
  '117': 'INDOOR_ROWING',
  '118': 'SPINNING',
  '119': 'STREET_DANCING',
  '120': 'LATIN_DANCING',
  '121': 'SHOW_DANCING',
  '122': 'BALLET_DANCING',
  '123': 'JAZZ_DANCING',
  '124': 'MODERN_DANCING',
  '125': 'BALLROOM_DANCING',
  '126': 'CORE',
  '127': 'MOBILITY_STATIC',
  '128': 'LES_MILLS_BODYPUMP',
  '129': 'LES_MILLS_BODYATTACK',
  '130': 'LES_MILLS_BODYCOMBAT',
  '131': 'LES_MILLS_GRIT_CARDIO',
  '132': 'LES_MILLS_GRIT_STRENGTH',
  '133': 'LES_MILLS_GRIT_PLYO',
  '134': 'LES_MILLS_SHBAM',
  '135': 'LES_MILLS_RPM',
  '136': 'LES_MILLS_BODYJAM',
  '137': 'LES_MILLS_BODYSTEP',
  '138': 'LES_MILLS_SPRINT',
  '139': 'LES_MILLS_BODYVIVE',
  '140': 'LES_MILLS_BODYBALANCE',
  '141': 'LES_MILLS_TRIP',
  '142': 'LES_MILLS_CXWORKS',
  '143': 'LES_MILLS_BARRE',
  '144': 'FITNESS_BOXING',
  '147': 'CURLING',
  '148': 'KETTLEBELL',
  '149': 'KICKBIKE',
  '153': 'OBSTACLE_COURSE_RACING',
  '154': 'RINGETTE',
  '155': 'SHOOTING_SPORT_OUTDOOR',
  '156': 'SKATEBOARDING',
  '157': 'SUP',
  '158': 'TAEKWONDO_MARTIAL_ARTS',
  '163': 'WATER_RUNNING',
  '164': 'WATER_EXERCISE',
  '173': 'MOTORSPORTS',
  '174': 'MOTORSPORTS_HARD_ENDURO',
  '175': 'MOTORSPORTS_CAR_RACING',
  '176': 'PADEL',
  '177': 'E_BIKE',
  '178': 'CROSS_COUNTRY_RUNNING',
  '179': 'VERTICALSPORTS_OUTCLIMBING',
  '180': 'MOTORSPORTS_ENDURO',
  '181': 'MOTORSPORTS_ROADRACING',
  '182': 'MOTORSPORTS_SNOCROSS',
  '183': 'MOTORSPORTS_MOTOCROSS',
  '184': 'JUMP_ROPE',
  '185': 'STAIR_WORKOUT',
  '186': 'ULTIMATE',
  '187': 'PARASPORTS_SLED_HOCKEY',
  '188': 'PICKLEBALL',
  '189': 'PARASPORTS_HAND_CYCLING',
  '190': 'AGILITY',
  '191': 'ESPORTS',
  '192': 'PARASPORTS_WHEELCHAIR_BASKETBALL',
  '193': 'PARASPORTS_WHEELCHAIR_TENNIS',
  '194': 'SHOOTING_SPORT_INDOOR',
  '195': 'GRAVEL',
  '196': 'PARASPORTS_WATER_SKIING',
  '197': 'BEACH_TENNIS',
  '202': 'HYROX',
  '203': 'RUCKING',
  '204': 'CALISTHENICS',
  '205': 'SKIERG'
};

const FIT_SPORT_MAPPING: Record<string, FitSportMapping> = {
  RUNNING: { sport: 'running', subSport: 'generic' },
  ROAD_RUNNING: { sport: 'running', subSport: 'street' },
  TRAIL_RUNNING: { sport: 'running', subSport: 'trail' },
  TREADMILL_RUNNING: { sport: 'running', subSport: 'treadmill' },
  JOGGING: { sport: 'running', subSport: 'generic' },
  TRACK_AND_FIELD_RUNNING: { sport: 'running', subSport: 'track' },
  ULTRARUNNING_RUNNING: { sport: 'running', subSport: 'ultra' },
  CROSS_COUNTRY_RUNNING: { sport: 'running', subSport: 'trail' },
  OBSTACLE_COURSE_RACING: { sport: 'running', subSport: 'obstacle' },
  ORIENTEERING: { sport: 'running', subSport: 'navigate' },
  TRIATHLON_RUNNING: { sport: 'running', subSport: 'generic' },
  DUATHLON_RUNNING: { sport: 'running', subSport: 'generic' },
  OFFROADTRIATHLON_RUNNING: { sport: 'running', subSport: 'trail' },
  OFFROADDUATHLON_RUNNING: { sport: 'running', subSport: 'trail' },

  CYCLING: { sport: 'cycling', subSport: 'generic' },
  ROAD_BIKING: { sport: 'cycling', subSport: 'road' },
  ROAD_CYCLING: { sport: 'cycling', subSport: 'road' },
  MOUNTAIN_BIKING: { sport: 'cycling', subSport: 'mountain' },
  INDOOR_CYCLING: { sport: 'cycling', subSport: 'indoorCycling' },
  SPINNING: { sport: 'cycling', subSport: 'spin' },
  GRAVEL: { sport: 'cycling', subSport: 'gravelCycling' },
  GRAVEL_CYCLING: { sport: 'cycling', subSport: 'gravelCycling' },
  E_BIKE: { sport: 'eBiking', subSport: 'generic' },
  E_BIKE_CYCLING: { sport: 'eBiking', subSport: 'generic' },
  KICKBIKE: { sport: 'cycling', subSport: 'generic' },
  TRIATHLON_CYCLING: { sport: 'cycling', subSport: 'generic' },
  DUATHLON_CYCLING: { sport: 'cycling', subSport: 'generic' },
  OFFROADTRIATHLON_CYCLING: { sport: 'cycling', subSport: 'mountain' },
  OFFROADDUATHLON_CYCLING: { sport: 'cycling', subSport: 'mountain' },
  ORIENTEERING_MTB: { sport: 'cycling', subSport: 'navigate' },
  PARASPORTS_HAND_CYCLING: { sport: 'cycling', subSport: 'handCycling' },

  WALKING: { sport: 'walking', subSport: 'generic' },
  NORDIC_WALKING: { sport: 'walking', subSport: 'generic' },
  HIKING: { sport: 'hiking', subSport: 'generic' },
  TREKKING: { sport: 'hiking', subSport: 'generic' },
  RUCKING: { sport: 'hiking', subSport: 'rucking' },
  SNOWSHOE_TREKKING: { sport: 'snowshoeing', subSport: 'generic' },

  CROSS_COUNTRY_SKIING: { sport: 'crossCountrySkiing', subSport: 'generic' },
  CROSS_COUNTRY_SKIING_CLASSIC: { sport: 'crossCountrySkiing', subSport: 'generic' },
  CROSS_COUNTRY_SKIING_SKATING: { sport: 'crossCountrySkiing', subSport: 'skateSkiing' },
  XC_SKIING_CLASSIC: { sport: 'crossCountrySkiing', subSport: 'generic' },
  XC_SKIING_FREESTYLE: { sport: 'crossCountrySkiing', subSport: 'skateSkiing' },
  ROLLER_SKIING_CLASSIC: { sport: 'crossCountrySkiing', subSport: 'generic' },
  ROLLER_SKIING_FREESTYLE: { sport: 'crossCountrySkiing', subSport: 'skateSkiing' },
  DOWNHILL_SKIING: { sport: 'alpineSkiing', subSport: 'resort' },
  BACKCOUNTRY_SKIING: { sport: 'alpineSkiing', subSport: 'backcountry' },
  TELEMARK_SKIING: { sport: 'alpineSkiing', subSport: 'backcountry' },
  SNOWBOARDING: { sport: 'snowboarding', subSport: 'resort' },
  BIATHLON: { sport: 'crossCountrySkiing', subSport: 'generic' },
  CURLING: { sport: 'winterSport', subSport: 'generic' },

  SWIMMING: { sport: 'swimming', subSport: 'generic' },
  POOL_SWIMMING: { sport: 'swimming', subSport: 'lapSwimming' },
  OPEN_WATER_SWIMMING: { sport: 'swimming', subSport: 'openWater' },
  TRIATHLON_SWIMMING: { sport: 'swimming', subSport: 'openWater' },
  OFFROADTRIATHLON_SWIMMING: { sport: 'swimming', subSport: 'openWater' },
  AQUATICS: { sport: 'waterSport', subSport: 'generic' },
  WATER_RUNNING: { sport: 'waterSport', subSport: 'generic' },
  WATER_EXERCISE: { sport: 'waterSport', subSport: 'generic' },
  WATERSPORTS_CANOEING: { sport: 'canoeing', subSport: 'generic' },
  WATERSPORTS_KAYAKING: { sport: 'kayaking', subSport: 'generic' },
  WATERSPORTS_KITESURFING: { sport: 'kitesurfing', subSport: 'generic' },
  WATERSPORTS_SAILING: { sport: 'sailing', subSport: 'generic' },
  WATERSPORTS_SURFING: { sport: 'surfing', subSport: 'generic' },
  WATERSPORTS_WAKEBOARDING: { sport: 'wakeboarding', subSport: 'generic' },
  WATERSPORTS_WATERSKI: { sport: 'waterSkiing', subSport: 'generic' },
  WATERSPORTS_WINDSURFING: { sport: 'windsurfing', subSport: 'generic' },
  PARASPORTS_WATER_SKIING: { sport: 'waterSkiing', subSport: 'generic' },
  SUP: { sport: 'standUpPaddleboarding', subSport: 'generic' },

  ROWING: { sport: 'rowing', subSport: 'generic' },
  INDOOR_ROWING: { sport: 'rowing', subSport: 'indoorRowing' },
  CROSS_TRAINER: { sport: 'fitnessEquipment', subSport: 'elliptical' },
  FITNESS_STEP: { sport: 'fitnessEquipment', subSport: 'stairClimbing' },
  STAIR_WORKOUT: { sport: 'fitnessEquipment', subSport: 'stairClimbing' },
  SKIERG: { sport: 'fitnessEquipment', subSport: 'indoorSkiing' },

  STRENGTH_TRAINING: { sport: 'training', subSport: 'strengthTraining' },
  FITNESS: { sport: 'training', subSport: 'cardioTraining' },
  GROUP_EXERCISE: { sport: 'training', subSport: 'generic' },
  CIRCUIT_TRAINING: { sport: 'training', subSport: 'exercise' },
  FUNCTIONAL_TRAINING: { sport: 'training', subSport: 'exercise' },
  BOOTCAMP: { sport: 'training', subSport: 'exercise' },
  AEROBICS: { sport: 'training', subSport: 'cardioTraining' },
  PILATES: { sport: 'training', subSport: 'pilates' },
  STRETCHING: { sport: 'training', subSport: 'flexibilityTraining' },
  YOGA: { sport: 'training', subSport: 'yoga' },
  CORE: { sport: 'training', subSport: 'exercise' },
  KETTLEBELL: { sport: 'training', subSport: 'strengthTraining' },
  GYMNASTICK: { sport: 'training', subSport: 'exercise' },
  CALISTHENICS: { sport: 'training', subSport: 'exercise' },
  HYROX: { sport: 'hiit', subSport: 'generic' },
  HIIT: { sport: 'hiit', subSport: 'hiit' },
  LES_MILLS_GRIT_CARDIO: { sport: 'hiit', subSport: 'hiit' },
  LES_MILLS_GRIT_STRENGTH: { sport: 'hiit', subSport: 'hiit' },
  LES_MILLS_GRIT_PLYO: { sport: 'hiit', subSport: 'hiit' },
  LES_MILLS_SPRINT: { sport: 'hiit', subSport: 'hiit' },
  LES_MILLS_BODYATTACK: { sport: 'training', subSport: 'cardioTraining' },
  LES_MILLS_BODYBALANCE: { sport: 'training', subSport: 'yoga' },
  LES_MILLS_BODYCOMBAT: { sport: 'boxing', subSport: 'generic' },
  LES_MILLS_BODYPUMP: { sport: 'training', subSport: 'strengthTraining' },
  LES_MILLS_BODYSTEP: { sport: 'fitnessEquipment', subSport: 'stairClimbing' },
  LES_MILLS_BARRE: { sport: 'training', subSport: 'exercise' },
  LES_MILLS_CXWORKS: { sport: 'training', subSport: 'exercise' },
  LES_MILLS_RPM: { sport: 'cycling', subSport: 'spin' },
  LES_MILLS_TRIP: { sport: 'cycling', subSport: 'indoorCycling' },

  MOBILITY_DYNAMIC: { sport: 'mobility', subSport: 'generic' },
  MOBILITY_STATIC: { sport: 'mobility', subSport: 'generic' },
  BODY_AND_MIND: { sport: 'meditation', subSport: 'generic' },

  DANCING: { sport: 'dance', subSport: 'generic' },
  FITNESS_DANCING: { sport: 'dance', subSport: 'generic' },
  STREET_DANCING: { sport: 'dance', subSport: 'generic' },
  LATIN_DANCING: { sport: 'dance', subSport: 'generic' },
  SHOW_DANCING: { sport: 'dance', subSport: 'generic' },
  BALLET_DANCING: { sport: 'dance', subSport: 'generic' },
  JAZZ_DANCING: { sport: 'dance', subSport: 'generic' },
  MODERN_DANCING: { sport: 'dance', subSport: 'generic' },
  BALLROOM_DANCING: { sport: 'dance', subSport: 'generic' },
  LES_MILLS_BODYJAM: { sport: 'dance', subSport: 'generic' },
  LES_MILLS_SHBAM: { sport: 'dance', subSport: 'generic' },

  MARTIAL_ARTS: { sport: 'mixedMartialArts', subSport: 'generic' },
  FITNESS_MARTIAL_ARTS: { sport: 'mixedMartialArts', subSport: 'generic' },
  JUDO_MARTIAL_ARTS: { sport: 'mixedMartialArts', subSport: 'generic' },
  TAEKWONDO_MARTIAL_ARTS: { sport: 'mixedMartialArts', subSport: 'generic' },
  KICKBOXING: { sport: 'boxing', subSport: 'generic' },
  KICKBOXING_MARTIAL_ARTS: { sport: 'boxing', subSport: 'generic' },
  BOXING: { sport: 'boxing', subSport: 'generic' },
  FITNESS_BOXING: { sport: 'boxing', subSport: 'generic' },

  TENNIS: { sport: 'tennis', subSport: 'generic' },
  SQUASH: { sport: 'racket', subSport: 'squash' },
  BADMINTON: { sport: 'racket', subSport: 'badminton' },
  TABLE_TENNIS: { sport: 'racket', subSport: 'tableTennis' },
  PADEL: { sport: 'racket', subSport: 'padel' },
  PICKLEBALL: { sport: 'racket', subSport: 'pickleball' },
  BEACH_TENNIS: { sport: 'racket', subSport: 'platform' },

  SOCCER: { sport: 'soccer', subSport: 'generic' },
  FUTSAL: { sport: 'soccer', subSport: 'generic' },
  CRICKET: { sport: 'cricket', subSport: 'generic' },
  BASKETBALL: { sport: 'basketball', subSport: 'generic' },
  BASEBALL: { sport: 'baseball', subSport: 'generic' },
  FINNISH_BASEBALL: { sport: 'baseball', subSport: 'generic' },
  RUGBY: { sport: 'rugby', subSport: 'generic' },
  FIELD_HOCKEY: { sport: 'hockey', subSport: 'field' },
  ICE_HOCKEY: { sport: 'hockey', subSport: 'ice' },
  VOLLEYBALL: { sport: 'volleyball', subSport: 'generic' },
  BEACH_VOLLEYBALL: { sport: 'volleyball', subSport: 'generic' },
  AMERICAN_FOOTBALL: { sport: 'americanFootball', subSport: 'generic' },
  HANDBALL: { sport: 'teamSport', subSport: 'generic' },
  FLOORBALL: { sport: 'teamSport', subSport: 'generic' },
  ULTIMATE: { sport: 'teamSport', subSport: 'ultimate' },

  TRIATHLON: { sport: 'multisport', subSport: 'triathlon' },
  DUATHLON: { sport: 'multisport', subSport: 'duathlon' },
  OFFROADTRIATHLON: { sport: 'multisport', subSport: 'triathlon' },
  OFFROADDUATHLON: { sport: 'multisport', subSport: 'duathlon' },
  FREE_MULTISPORT: { sport: 'multisport', subSport: 'generic' },

  SKATING: { sport: 'iceSkating', subSport: 'generic' },
  ICE_SKATING: { sport: 'iceSkating', subSport: 'generic' },
  INLINE_SKATING: { sport: 'inlineSkating', subSport: 'generic' },
  ROLLER_BLADING: { sport: 'inlineSkating', subSport: 'generic' },
  JUMP_ROPE: { sport: 'jumpRope', subSport: 'generic' },

  GOLF: { sport: 'golf', subSport: 'generic' },
  FRISBEEGOLF: { sport: 'discGolf', subSport: 'generic' },
  TROTTING: { sport: 'horsebackRiding', subSport: 'generic' },
  RIDING: { sport: 'horsebackRiding', subSport: 'generic' },
  SHOOTING_SPORT_OUTDOOR: { sport: 'shooting', subSport: 'generic' },
  SHOOTING_SPORT_INDOOR: { sport: 'shooting', subSport: 'generic' },
  ESPORTS: { sport: 'videoGaming', subSport: 'esport' },

  VERTICALSPORTS_WALLCLIMBING: { sport: 'rockClimbing', subSport: 'indoorClimbing' },
  VERTICALSPORTS_OUTCLIMBING: { sport: 'rockClimbing', subSport: 'generic' },
  CLIMBING_OUTDOOR: { sport: 'rockClimbing', subSport: 'generic' },
  INDOOR_CLIMBING: { sport: 'rockClimbing', subSport: 'indoorClimbing' },
  BOULDERING: { sport: 'rockClimbing', subSport: 'bouldering' },

  PARASPORTS_WHEELCHAIR: { sport: 'paraSport', subSport: 'generic' },
  PARASPORTS_WHEELCHAIR_BASKETBALL: { sport: 'paraSport', subSport: 'generic' },
  PARASPORTS_WHEELCHAIR_TENNIS: { sport: 'paraSport', subSport: 'generic' },
  PARASPORTS_SLED_HOCKEY: { sport: 'paraSport', subSport: 'generic' },

  MOTORSPORTS: { sport: 'motorSports', subSport: 'generic' },
  MOTORSPORTS_CAR_RACING: { sport: 'motorSports', subSport: 'rally' },
  MOTORSPORTS_ENDURO: { sport: 'motorcycling', subSport: 'generic' },
  MOTORSPORTS_HARD_ENDURO: { sport: 'motorcycling', subSport: 'generic' },
  MOTORSPORTS_MOTOCROSS: { sport: 'motorcycling', subSport: 'motocross' },
  MOTORSPORTS_ROADRACING: { sport: 'motorcycling', subSport: 'generic' },
  MOTORSPORTS_SNOCROSS: { sport: 'snowmobiling', subSport: 'generic' }
};

export function mapPolarSportToFit(value: unknown): FitSportMapping {
  const normalized = normalizeSportKey(value);
  const polarSport = normalized ? POLAR_FLOW_SPORT_ID_TO_KIND[normalized] ?? normalized : null;
  const mapping = polarSport ? FIT_SPORT_MAPPING[polarSport] : undefined;
  if (mapping) {
    return mapping;
  }
  return {
    sport: 'generic',
    subSport: 'generic',
    warning: polarSport
      ? `Nieobsługiwany sport Polar dla FIT: ${polarSport}. Użyto generic.`
      : 'Brak sportu Polar dla FIT. Użyto generic.'
  };
}

function normalizeSportKey(value: unknown): string | null {
  if (value === null || value === undefined || value === '') {
    return null;
  }
  return String(value).trim().toUpperCase().replace(/[-\s]+/g, '_');
}
